### ISSUE TITLE
error when reloading .git/index file 

### ISSUE THREAD

**Issue by huangyingw** [pseewald/AnyFold#13]
Hi, 
    When I reload a .git/index file in vim, I got following errors:
------
E121: Undefined variable: b:anyfold_ind_actual
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E116: Invalid arguments for function len(b:anyfold_ind_actual)
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E15: Invalid expression: line('$') - len(b:anyfold_ind_actual)
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E121: Undefined variable: b:anyfold_ind_actual
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E116: Invalid arguments for function len(b:anyfold_ind_actual)
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E15: Invalid expression: line('$') - len(b:anyfold_ind_actual)
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E121: Undefined variable: b:anyfold_ind_actual
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E116: Invalid arguments for function len(b:anyfold_ind_actual)
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E15: Invalid expression: line('$') - len(b:anyfold_ind_actual)
Press ENTER or type command to continue
Error detected while processing function <SNR>112_ReloadFolds:
line   14:
E121: Undefined variable: b:anyfold_ind_actual

**Comment by pseewald** [comment]
I can not reproduce this issue. Could you give a minimal example?

**Comment by huangyingw** [comment]
Sorry, I could not reproduce this now.
