### ISSUE TITLE
Fail when reload a changed php file.

### ISSUE THREAD

**Issue by huangyingw** [pseewald/AnyFold#15]
For example, this php code block.
`			default:
				echo("ERROR: Invalid vm kind '$kind'\n");
				usage();
				die();
`
This is my dropbox link to the php file:
https://www.dropbox.com/s/lmquuigc5ysot0v/zend_vm_gen.php?dl=0
The first time, it could fold on "default:". While, if I check out to another git commit/branch from outside, and inside vim, therefore, I reload it, then it will say
E490: No fold found
I have tested the similar scenario for python file, it works.
I really love your plugin, I am trying to fix this issue, if you could help, greatly appreciate.

**Comment by pseewald** [comment]
Thanks a lot for the pull request! I'd be happy to merge it but I still can't confirm the issue. If it is an issue with the way vim-anyfold is initialised, it should be reproducible with any filetype. You said there are no problems with python files? Is there something in your vimrc that sets options only for php files (such as foldmethod) that interfer with vim-anyfold? vim-anyfold is not re-initialised if you reload a file. This works fine unless you have a `autocmd Filetype php` command in your vimrc that conflicts with vim-anyfold...

**Comment by huangyingw** [comment]
The only php specific foldmethod for my vim are
./macvim/runtime/syntax/php.vim:449:  set foldmethod=syntax
./macvim/runtime/syntax/php.vim:463:    set foldmethod=syntax
They are vim default run time, should I change these and re-compile my macvim ?

**Comment by huangyingw** [comment]
@pseewald Just come up with a method to verify at your side: have 2 different php files under the same folder, say test1.php, test2.php
Vi test1.php
And then under vi, run 
:!cp test2.php test1.php
This will force the buffer to reload, then I think you could see that the folding is not working.

**Comment by pseewald** [comment]
Ok I understand the issue. I think syntax scripts should not set foldmethod. But I agree that vim-anyfold should make sure that foldmethod (and possibly other defaults) can not be changed by another plugin if the file is reloaded. I will quickly test your pull request and then merge it.
