### ISSUE TITLE
Folding Import/include statements

### ISSUE THREAD

**Issue by nirajgup** [pseewald/AnyFold#18]
vim-anyfold doesn't fold import/include statements currently.

We should fold #import/#include statements for java, cpp, c, python etc.
Most major IDEs currently do this.

**Comment by pseewald** [comment]
This is supported by vim-anyfold but not enabled by default. For java, cpp, c, python, the following configuration should work:
```vim
autocmd filetype java,cpp,c,python let b:anyfold_activate=1
autocmd filetype cpp,c let g:anyfold_identify_comments=1
autocmd filetype python,java let g:anyfold_identify_comments=2
let g:anyfold_fold_comments=1
let g:anyfold_comments=['comment','string','external','include']
```

**Comment by nirajgup** [comment]
Thanks!

The suggested configuration works. I will close the issue.
