### ISSUE TITLE
vim-anyfold is adding jumps to jumplist

### ISSUE THREAD

**Issue by nirajgup** [pseewald/AnyFold#19]
# Opening a file with folds messes up the jump list.

# Replication steps

1. Open a file for the first time with folds and let **vim-anyfold** fold the file
1. Press `[ctrl - O]` repetitively to traverse back the jump list
1. Notice it traverses through all the folds one by one 
1. You can view the jump stack by calling `:jump` command.

# Possible Solution
We can make use of `:keepjumps` command to keep the jumplist intact.
Please read `:help :keepjumps`

**Comment by pseewald** [comment]
Thank you for letting me know, it should be fixed now.
