### ISSUE TITLE
doesn't work with vim-plug

### ISSUE THREAD

**Issue by 0x8f701** [pseewald/AnyFold#32]
when use vim-anyfold together with vim-plug I always got errors while running:

```
:PlugInstall
```

**Comment by pseewald** [comment]
Sorry for the late response. Are you sure it's an issue with vim-anyfold or is it an issue of vim-plug? What's the error message?

**Comment by 0x8f701** [comment]
@pseewald Hi, no problem, actually I'm not sure if it's problem of vim-anyfold & vim-plug, but I believe they don't work with each other, or not stable, sometimes I got error message sometimes no.

**Comment by 0x8f701** [comment]
The error message is:

```
Error detected while processing function <SNR>7_nvim_cb[1]..<SNR>7_job_cb[4]..<SNR>7_job_out_cb[10]..<SNR>7_log[2]..<SNR>7_logpos:
line    1:                                                                                                                                                                          
E727: Start past end
Press ENTER or type command to continue
Error detected while processing function <SNR>7_nvim_cb[1]..<SNR>7_job_cb[4]..<SNR>7_job_out_cb[10]..<SNR>7_log[2]..<SNR>7_logpos:
line    1:
E714: List required
Press ENTER or type command to continue
Error detected while processing function <SNR>7_nvim_cb[1]..<SNR>7_job_cb[4]..<SNR>7_job_out_cb[10]..<SNR>7_log[2]..<SNR>7_logpos:
line    1:
E727: Start past end
Press ENTER or type command to continue
Error detected while processing function <SNR>7_nvim_cb[1]..<SNR>7_job_cb[4]..<SNR>7_job_out_cb[10]..<SNR>7_log[2]..<SNR>7_logpos:
line    1:
E714: List required
Press ENTER or type command to continue
Error detected while processing function <SNR>7_nvim_cb[1]..<SNR>7_job_cb[4]..<SNR>7_job_out_cb[10]..<SNR>7_log[2]..<SNR>7_logpos:
line    1:
E727: Start past end
Press ENTER or type command to continue
Error detected while processing function <SNR>7_nvim_cb[1]..<SNR>7_job_cb[4]..<SNR>7_job_out_cb[10]..<SNR>7_log[2]..<SNR>7_logpos:
line    1:
E714: List required
Press ENTER or type command to continue
```

**Comment by 0x8f701** [comment]
Sometimes `vim-anyfold` can cause plugin list to disappear as you can see from here:

https://user-images.githubusercontent.com/33961674/71797882-ec854b00-308a-11ea-9852-52f93e14290d.gif

**Comment by pseewald** [comment]
Are you using `autocmd Filetype * AnyFoldActivate`? This enables anyfold also for buffers that are managed by other plugins, for sure this can cause bad interactions. Instead I recommend to enable anyfold only for specific filetypes.

**Comment by 0x8f701** [comment]
@pseewald Hi, I do have this in my vimrc

**Comment by pseewald** [comment]
Could you then replace this with something like `autocmd Filetype python, cpp AnyFoldActivate` (or whatever filetypes you want) and let me know if this solves these issues?

**Comment by 0x8f701** [comment]
@pseewald cool, seems fixed my issue. 

BTW, I notice always a strange fold:

![Peek 2020-08-04 10-12](https://user-images.githubusercontent.com/33961674/89270100-262b2e00-d63b-11ea-952b-d43cc05eb2ba.gif)

As you can see from the above git, if I put my cursur on `HttpServer` or `App` the fold is ok, but if I put my cursor on `.bind`, it folds also the following lines which isn't convinient, is it possible to make it stop before empty lines?

**Comment by pseewald** [comment]
I don't see what's the problem here, for me this looks as expected. Empty lines don't define a new scope so everything below `.bind` should belong to the fold.

If my suggestion fixed this issue, I'll close it.

**Comment by 0x8f701** [comment]
@pseewald  I think fold should stop just before empty line instead of including it.

when I call `fold` on `.bind` it nearly folded the whole file which isn't ideal
