### ISSUE TITLE
Errors in neovim when opening built-in terminal

### ISSUE THREAD

**Issue by moon-musick** [pseewald/AnyFold#8]
Hi,

it seems running `:vsplit term://top` or even `term://bash` in `neovim` (`v0.2.1-dev` from official Ubuntu PPA, Ubuntu 16.04 amd64, ), actually an example taken directly from [neovim documentation](https://neovim.io/doc/user/nvim_terminal_emulator.html) yields `Error detected while processing function <SNR>195_ReloadFolds`. 

I suppose it is not really a good idea to fold terminal content - `anyfold` could most likely be safely disabled in some way for this type of buffer. I could do that in my vimrc, but I have no idea how to do that. Could you perhaps point me in the right direction?

**Comment by pseewald** [comment]
I agree that anyfold should always be deactivated for this buffer type. This should be implemented by adding this case to `b:anyfold_disable` in [this line](https://github.com/pseewald/vim-anyfold/blob/master/autoload/anyfold.vim#L23).

Can you test this and create a pull request if you can fix this?

**Comment by moon-musick** [comment]
PR in #9
